package prob11to20;

/**
 * Problem 12
 * The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:

1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

Let us list the factors of the first seven triangle numbers:

 1: 1
 3: 1,3
 6: 1,2,3,6
10: 1,2,5,10
15: 1,3,5,15
21: 1,3,7,21
28: 1,2,4,7,14,28
We can see that 28 is the first triangle number to have over five divisors.

What is the value of the first triangle number to have over five hundred divisors?
 * @author Duke
 *
 */
public class HighlyDivisibleTriangularNumber {
	public static void main(String[] args){
		findTriangleNumber(500);
	}
	
	//Brute force method
	private static void findTriangleNumber(int n){
		int index = 1;
		int maxDivisors = 1;
		int a=2,temp=0;
		while(maxDivisors<=n){
			index = index +a;
			temp = divisorCount(index);
			if(temp>maxDivisors){
				maxDivisors = temp;
			}
			a++;
		}
		System.out.println(index);
		
	}
	private static int divisorCount(int n){
		int count = 2;
		for(int i = 2; i<=Math.sqrt(n);i++){
			if(n%i==0){
				count+=2;
			}
		}
		return count;
		
	}
}
